# Generated by Django 3.2.4 on 2021-06-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory', models.CharField(max_length=10)),
                ('loc', models.CharField(max_length=10)),
                ('endUser', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=10)),
                ('unitPrice', models.IntegerField()),
                ('acqDate', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
