# Generated by Django 3.2.4 on 2021-06-23 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='brand',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
